spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  application:
    name: Journal App
  data:
    mongodb:
      uri: ${MONGO_DB_CONNECTION_URI}
      database: journal_app
      index-creation:
        enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

server:
    port: 8080


#Weater Stack API Key
my:
  weather:
      api:
        key: ${WEATHER_STACK_API_KEY}

#JWT
JWT_SECRET_KEY: ${JWT_SECRET_KEY}